= Encryption

== Database
Our database requires that the following data are stored per one user entry:
- Account ID#
- Account Balance
- First Name (of User)
- Middle Name
- Last Name
- Transaction History
- Password (Hashed)
- Salt

On the server the following is stored:
- Java Keystore
The Java Keystore will store all the AES keys of the users, and will be locked by a master password

== Procedure

1. User downloads and installs application (Assume this is done magically for now)

When a new user entry is made, we will need to do the following:
- Create a new AES Key, IV, Salt
- Obtain User's password
- Generate cipherText from the AES Key, IV, Salt and password

2. Sending to Server

Preparation:

To send the data to the server, the application will prepare the data into a .json file with the following data encoded as a base64 String:
- cipherText (Contains IV, Salt, Password, and is a hash)
- AES Key (file)

Sending:

TODO: Configure SSL/TLS with Certs & Perms (Self-Signed)
TODO: Make Mock server to test client-side only

The data will be sent over SSL/TLS to the server, and perform the magic.

3. Data Preparation

The data will be acessed from the .json file, and will be extracted by the PHP frontend or Java systemd service (More likely). 

*Data Extraction Process:*
- Base64 cipherText, AES Key (Base64) -> cipherText -> IV, Salt, cipherText 

Either way, in the database, the DB will create new user entries as follows:
- Account ID#
- Account Balance
- First Name (of User)
- Middle Name
- Last Name
- Transaction History
- Password (Hashed)
- Salt

PHP will be used to expose the functionality to the client application. (Or a newer, more modern alternative depending on the reqs).

